### PR TITLE
Update to ViewController and README

### PR DESCRIPTION
**Pull request by spaz926**
Updated ViewController to now use constants instead of the user needing to edit each token on lines all over ViewController file.

Updated README to reflect changes to ViewController.

### CODE REVIEW

**Comment by spaz926** [comment]
The reason there is two edits is because I accidentally put it inside of the ViewController class.

**Comment by adambowles** [comment]
Looks like you left your personal keys in there

**Comment by spaz926** [comment]
Well that was stupid. I'll fix it when I get back to my computer.

I'd like to figure out how to make it a request from the user to enter their info on launch of the application. I'm not well versed in Swift though and would probably mess something up. But it would prevent stupid mistakes such as this.

**Comment by adambowles** [comment]
Haha, it happens, I suggest you regenerate those keys where possible.

I agree on the GUI setup, I'm also not knowlegable in Swift unfortunately.

**Comment by spaz926** [comment]
Closed in favor of #38

**Pull request closed without merging**
